import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "background": "#fff8f6",
        "primary-fixed": "#ffdbd1",
        "surface-container": "#ffe9e4",
        "on-tertiary-fixed-variant": "#5f4100",
        "on-primary-container": "#ffc4b4",
        "error-container": "#ffdad6",
        "tertiary": "#593d00",
        "on-tertiary-fixed": "#271900",
        "inverse-primary": "#ffb5a0",
        "on-primary-fixed-variant": "#842508",
        "tertiary-fixed-dim": "#fabc44",
        "tertiary-fixed": "#ffdeaa",
        "on-secondary-container": "#723a00",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-container": "#785300",
        "surface-container-low": "#fff1ed",
        "on-surface-variant": "#57423c",
        "secondary": "#924c00",
        "surface-tint": "#a43c1e",
        "primary-container": "#9e381a",
        "inverse-surface": "#402c26",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb780",
        "surface-container-high": "#ffe2da",
        "on-secondary-fixed-variant": "#6f3800",
        "on-primary-fixed": "#3b0900",
        "surface-container-highest": "#fddbd3",
        "surface-bright": "#fff8f6",
        "outline": "#8b716b",
        "on-primary": "#ffffff",
        "secondary-container": "#ffa358",
        "surface-variant": "#fddbd3",
        "on-surface": "#291712",
        "on-secondary-fixed": "#2f1400",
        "primary": "#7e2104",
        "primary-fixed-dim": "#ffb5a0",
        "on-background": "#291712",
        "surface": "#fff8f6",
        "outline-variant": "#dec0b8",
        "on-tertiary-container": "#ffc96a",
        "on-secondary": "#ffffff",
        "surface-dim": "#f4d3ca",
        "inverse-on-surface": "#ffede8",
        "secondary-fixed": "#ffdcc4",
        "on-tertiary": "#ffffff"
      },
      fontFamily: {
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
